### ISSUE TITLE
Is there a Swift version or example of how to use in Swift?

### ISSUE THREAD

**Issue by MartinOrtiz** [intuit/AnimationEngine#4]
I'm new to apple programming, and am learning only swift language.

Is there a swift version of this library? Or a an example of how to use in Swift?

**Comment by popara** [comment]
http://stackoverflow.com/questions/24002369/how-to-call-objective-c-code-from-swift

Make a ProjectName-Bridging-Header.h
In in 

#import "INTUAnimationEngine"

Add file as Bridging header file in your Build Settings [explained in the SO answer], and you are good to go to use it in Swift! :)
